global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@jewelrystore.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-simulator'

receivers:
- name: 'webhook-simulator'
  webhook_configs:
  - url: 'http://host.docker.internal:8090/webhook/prometheus-alerts'
    send_resolved: true
    http_config:
      follow_redirects: true 